#!/usr/bin/env php
<?php
namespace brown;
require __DIR__ . '/vendor/autoload.php';


use Symfony\Component\Console\Application;

$application = new Application();

// 注册我们编写的命令 (commands)
$application->add(new \brown\command\RpcRun());
$application->add(new \brown\command\ServerRun());
$application->add(new \brown\command\RpcDoc());


$application->run();

