<?php

namespace brown\command;




class Vendor
{


    public static function execute()
    {
        $now_path=dirname(__DIR__) . DIRECTORY_SEPARATOR;
        $root_path=dirname($now_path, 4) . DIRECTORY_SEPARATOR;
        $config_dir=$root_path.'config'.DIRECTORY_SEPARATOR;
//        parent::execute($input, $output); // TODO: Change the autogenerated stub

        if (is_file($composer_path=$root_path.'vendor/composer/installed.json')){

            $packages = json_decode(@file_get_contents($composer_path), true);
            if (isset($packages['packages'])) {
                $packages = $packages['packages'];
            }
            foreach ($packages as $package) {
                //配置

                if (!empty($package['extra']['brown']['command'])) {

                    $installPath = $root_path . 'vendor/' . $package['name'] . DIRECTORY_SEPARATOR;

                    foreach ((array) $package['extra']['brown']['command'] as $name => $file) {

                        $target = $installPath . $file ;

                        $source = $root_path.$name;

                        copy($target, $source);
                    }
                }

                if (!empty($package['extra']['brown']['config'])){
                    $installPath = $root_path . 'vendor/' . $package['name'] . DIRECTORY_SEPARATOR;

                    foreach ((array) $package['extra']['brown']['config'] as $name => $file) {
                        $target = $installPath . $file ;
                        $source = $config_dir.$name.'.php';
                        copy($target, $source);
                    }
                }
            }

        }
    }
}