<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_pack.proto

namespace GPBMetadata;

class ProtobufPack
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
?
protobuf_pack.proto	BrownGrpc"
Pack
value (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

