<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_pack.proto

namespace BrownGrpc;

if (false) {
    /**
     * This class is deprecated. Use BrownGrpc\NestedArray\InnerArray instead.
     * @deprecated
     */
    class NestedArray_InnerArray {}
}
class_exists(NestedArray\InnerArray::class);
@trigger_error('BrownGrpc\NestedArray_InnerArray is deprecated and will be removed in the next major release. Use BrownGrpc\NestedArray\InnerArray instead', E_USER_DEPRECATED);

